# Generated by Django 3.1.5 on 2021-05-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='published_lecture',
            name='publish_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
