# Generated by Django 3.1.5 on 2021-05-04 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_published_lecture_publish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='published_lecture',
            name='publish_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
