# Generated by Django 3.1.5 on 2021-05-04 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_auto_20210504_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='published_lecture',
            name='publish_time',
        ),
    ]
