# Generated by Django 2.2 on 2021-05-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_remove_published_lecture_publish_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stuedent_indentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_id', models.CharField(max_length=40, verbose_name='学生学号')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_indentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teacher_id', models.CharField(max_length=40, verbose_name='老师职工号')),
            ],
        ),
    ]
