# Generated by Django 3.1.5 on 2021-04-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GetPublish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='用户名')),
                ('reason', models.CharField(max_length=200, verbose_name='申请理由')),
                ('apply_time', models.CharField(max_length=30, verbose_name='申请时间')),
            ],
        ),
    ]
