# Generated by Django 3.1.5 on 2021-05-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sign_publish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_id', models.CharField(max_length=10, verbose_name='讲座id')),
                ('signPassword', models.CharField(max_length=30, verbose_name='签到密码')),
                ('p_id', models.CharField(max_length=20, verbose_name='发布人用户名')),
            ],
        ),
    ]
