# Generated by Django 2.2 on 2021-05-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_sign_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='lecture_experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, verbose_name='用户名')),
                ('l_id', models.CharField(max_length=10, verbose_name='讲座id')),
                ('title', models.CharField(max_length=200, verbose_name='讲座心得标题')),
                ('content', models.CharField(max_length=2000, verbose_name='讲座心得内容')),
            ],
        ),
    ]
