# Generated by Django 3.1.5 on 2021-04-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture_Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lecture_title', models.CharField(max_length=50, verbose_name='讲座标题')),
                ('Lecture_Pname', models.CharField(max_length=10, verbose_name='主讲人')),
                ('Lecture_introdution', models.CharField(max_length=300, verbose_name='讲座内容介绍')),
                ('Lecture_SN', models.CharField(max_length=10, verbose_name='讲座最大预约人数')),
                ('Lecture_category', models.CharField(max_length=20, verbose_name='讲座类型标签')),
                ('Lecture_Stime', models.CharField(max_length=20, verbose_name='讲座开始时间')),
                ('Lecture_Etime', models.CharField(max_length=20, verbose_name='讲座结束时间')),
                ('Lecture_Location', models.CharField(max_length=20, verbose_name='讲座地点')),
            ],
        ),
    ]
