# Generated by Django 3.1.5 on 2021-05-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture_message',
            name='Lecture_Location',
            field=models.CharField(max_length=50, verbose_name='讲座地点'),
        ),
        migrations.AlterField(
            model_name='lecture_message',
            name='Lecture_Pname',
            field=models.CharField(max_length=100, verbose_name='主讲人'),
        ),
        migrations.AlterField(
            model_name='lecture_message',
            name='Lecture_title',
            field=models.CharField(max_length=100, verbose_name='讲座标题'),
        ),
    ]
